import { PcfComponent } from '@gtui/gt-ui-framework';
import { PcfTextInput } from '@gtui/gt-ui-framework';
import { PcfButton } from '@gtui/gt-ui-framework';
import { PcfListView } from '@gtui/gt-ui-framework';

export class AGARatingCumulPopup {
	aGARatingCumulPopupAGARatingCumulPopup_UpLink = PcfButton('#AGARatingCumulPopup-AGARatingCumulPopup_UpLink');
	ratingCumulDetailsPanelSetAmountFooter = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-AmountFooter');
	ratingCumulDetailsPanelSetAmountHeader = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-AmountHeader');
	ratingCumulDetailsPanelSetBACoverageCostLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-BACoverageCostLV');
	ratingCumulDetailsPanelSetDescriptionFooter = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-DescriptionFooter');
	ratingCumulDetailsPanelSetDescriptionHeader = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-DescriptionHeader');
	ratingCumulDetailsPanelSetJurisdictionHeader = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-JurisdictionHeader');
	ratingOverrideButtonDVOverrideRating = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-RatingOverrideButtonDV-RatingOverrideButtonDV-OverrideRating');
	ratingOverrideButtonDVViewWorksheet = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-RatingOverrideButtonDV-RatingOverrideButtonDV-ViewWorksheet');
	ratingCumulDetailsPanelSetvehicleLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-vehicleLV');
	ratingCumulDetailsPanelSetAmount = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-Amount');
	ratingCumulDetailsPanelSetBuildingNumberHeader = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-BuildingNumberHeader');
	ratingCumulDetailsPanelSetDescription = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-Description');
	nonLocationCostIteratorAmountFooter = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-NonLocationCostIterator-AmountFooter');
	nonLocationCostIteratorAmountHeader = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-NonLocationCostIterator-AmountHeader');
	nonLocationCostIteratorDescriptionHeader = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-NonLocationCostIterator-DescriptionHeader');
	nonLocationCostIteratorStateHeader = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-NonLocationCostIterator-StateHeader');
	ratingCumulDetailsPanelSet_ViewDetail = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-_ViewDetail');
	ratingCumulDetailsPanelSetAdd = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-Add');
	ratingCumulDetailsPanelSetAmountHeading = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-AmountHeading');
	ratingCumulDetailsPanelSetCurrentTermHeading = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-CurrentTermHeading');
	ratingCumulDetailsPanelSetGroupHeading = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-GroupHeading');
	ratingCumulDetailsPanelSetRemove = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-Remove');
	ratingCumulDetailsPanelSetSettlementAmountHeading = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-SettlementAmountHeading');
	ratingCumulDetailsPanelSetTypeHeading = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-TypeHeading');
	ratingCumulDetailsPanelSet_ListPaging = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-_ListPaging');
	ratingCumulDetailsPanelSetcostLiabilityLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-costLiabilityLV');
	ratingCumulDetailsPanelSetcostOptionalLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-costOptionalLV');
	ratingCumulDetailsPanelSetlocationUseLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-locationUseLV');
	ratingCumulDetailsPanelSetsubTotalLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-subTotalLV');
	ratingCumulDetailsPanelSetRateCumulGLLineLevelCoverageLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-RateCumulGLLineLevelCoverageLV');
	adjustmentsToBasePremiumCostsHOPAdjustmentsToBasePremiumLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-AdjustmentsToBasePremiumCosts-HOPAdjustmentsToBasePremiumLV');
	basePremiumCostsHOPBasePremiumLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-BasePremiumCosts-HOPBasePremiumLV');
	modifierCostsHOPModifierCostLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-ModifierCosts-HOPModifierCostLV');
	otherPremiumCostsHOPOtherPremiumLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-OtherPremiumCosts-HOPOtherPremiumLV');
	totalCostHOPTotalCostLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-TotalCost-HOPTotalCostLV');
	iMRatingCumulPanelSet_ListPaging = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-IMRatingCumulPanelSet-_ListPaging');
	iMRatingCumulPanelSetpartPremiumHeader = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-IMRatingCumulPanelSet-partPremiumHeader');
	iMRatingCumulPanelSetpartnameHeader = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-IMRatingCumulPanelSet-partnameHeader');
	iMRatingCumulPanelSet_tbcompactviewButton = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-IMRatingCumulPanelSet_tb-compactviewButton');
	iMRatingCumulPanelSet_tbextendedviewButton = PcfButton('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-IMRatingCumulPanelSet_tb-extendedviewButton');
	ratingCumulDetailsPanelSetdriverLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-driverLV');
	ratingCumulDetailsPanelSetLiabilityLimit = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-LiabilityLimit');
	ratingCumulDetailsPanelSetPremium = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-Premium');
	ratingCumulDetailsPanelSetPremiumAmount = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-PremiumAmount');
	ratingCumulDetailsPanelSetumbcovretainedlimit = PcfTextInput('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-umbcovretainedlimit');
	liabilityPremiumCostsPRPLiabilityPremiumsLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-LiabilityPremiumCosts-PRPLiabilityPremiumsLV');
	otherPremiumCostsPRPOtherPremiumsLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-OtherPremiumCosts-PRPOtherPremiumsLV');
	totalCostPRPTotalCostLV = PcfListView('#AGARatingCumulPopup-RatingCumulDetailsPanelSet-TotalCost-PRPTotalCostLV');
	aGARatingCumulPopup_Paging = PcfButton('#AGARatingCumulPopup-_Paging');
	aGARatingCumulPopup__crumb__ = PcfComponent('#AGARatingCumulPopup-__crumb__');
	aGARatingCumulPopup_msgs = PcfButton('#AGARatingCumulPopup-_msgs');
}
