import world from "./world";

export class AutoGeneratedCustomMethod{

    async generateRandomText(lenghtOfText){

        let generatedText = '';
        let characterElements = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        let characterLength = characterElements.length;

        for (let i = 0; i < lenghtOfText; i++) {
            
            generatedText += characterElements.charAt( Math.floor( Math.random() * characterLength ));    

        }

        return generatedText;

    }

    async generateRandomBirthday(start,end){

        let myDate = new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));

        let myDay = myDate.getDate();
        let myMonth = myDate.getMonth() + 1;
        let myYear = myDate.getFullYear();

        if(myDay < 10)myDay = "0"+myDay;
        if(myMonth < 10)myMonth = "0"+myMonth;

        let generatedBirtday = myMonth.toString()+myDay.toString()+myYear.toString();

        world.PrimaryInsuredInformation.PersonalInfo.birthDate = generatedBirtday;

        return generatedBirtday;

    }

    async generateHomePhoneNumber(){

        let generatedHomePhoneNumber = '201';
        let characterElements = '0123456789';
        let characterLength = characterElements.length;

        for (let i = 0; i < 7; i++) {
            
            generatedHomePhoneNumber += characterElements.charAt( Math.floor( Math.random() * characterLength ));    

        }

        world.PrimaryInsuredInformation.PersonalInfo.homePhone = generatedHomePhoneNumber;

        return generatedHomePhoneNumber;

    }

    async generateSSNNumber(){


        let generatedSSNNumber = '';
        let characterElements = '0123456789';
        let characterLength = characterElements.length;

        for (let i = 0; i < 9; i++) {
            
            generatedSSNNumber += characterElements.charAt( Math.floor( Math.random() * characterLength ));    

        }

        world.PrimaryInsuredInformation.PersonalInfo.ssn = generatedSSNNumber;

        return generatedSSNNumber;

    }



}