import { PcfButton, PcfComponent, PcfListView } from "@gtui/gt-ui-framework";
import { t } from "testcafe";
import { PolicyInfoScreen } from "../../../pages/lOBWizardStepGroup/policyInfo/PolicyInfoScreen";
import { WorkersComp } from "../../../pages/lOBWizardStepGroup/WorkersComp";
import { IndustryCodeSearchPopup } from "../../../pages/popup/Industry/IndustryCodeSearchPopup";
import { WCClassCodeSearchPopup } from "../../../pages/popup/WCClass/WCClassCodeSearchPopup";
import { WorkersCompensationWizard } from "../../pages/WorkingCompensationWizard";
import { AutoGeneratedCustomMethod } from "../../util/AutoGeneratedCustomMethod";
import { CustomMethod } from "../../util/CustomMethod";
import { SubmissionScenario } from "./SubmissionScenario";
import world from "../../util/world";

const customMethod = new CustomMethod();
const policyInfoScreen = new PolicyInfoScreen();
const autoGeneratedCustomMethod = new AutoGeneratedCustomMethod();
const industryCodeSearchPopup = new IndustryCodeSearchPopup();
const workersComp = new WorkersComp();
const workersCompensationWizard = new WorkersCompensationWizard();
const wcClassCodeSearchPopup = new WCClassCodeSearchPopup();

export class WCCreationScenario extends SubmissionScenario{

    async createWorkersCompensationPolicy(){

        console.log('Policy Creation Start')
        await this.startSubmission("Workers' Compensation");

        //+----------Policy Info Screen----------+
        await this.navigateToPolicyScreen();
        await policyInfoScreen.policyOfficialIDInputSetOfficialIDDV_Input.setValue(await autoGeneratedCustomMethod.generateSSNNumber());
        await policyInfoScreen.submissionWizardLOBWizardStepGroupSubmissionWizard_PolicyInfoScreenSubmissionWizard_PolicyInfoDVAccountInfoInputSetIndustryCodeSelectIndustryCode.click();
        await industryCodeSearchPopup.industryCodeSearchScreenIndustryCodeSearchResultsLV.clickOnCell(3,0);
        await policyInfoScreen.accountInfoInputSetOrganizationType.selectOptionByLabel('Corporation - private');
        await policyInfoScreen.policyInfoInputSetWrittenDate.setValue(await customMethod.getPastDate(10));
        await policyInfoScreen.policyInfoInputSetEffectiveDate.setValue(await customMethod.getPastDate(10));

        //+----------Location Screen----------+
        await PcfButton(this.policyContractParent.find('div[id$="-Locations"]')).click();
        
        //+----------WC Coverage Screen----------+
        await PcfButton(this.policyContractParent.find('div[id$="-WorkersCompCoverageConfig"]')).click();
        await workersCompensationWizard.stateIds.setValue('123456789');
        await workersComp.submissionWizardLOBWizardStepGroupLineWizardStepSetWorkersCompCoverageConfigScreenWorkersCompCoverageCVWorkersCompClassesInputSetWCCovEmpLV_tbAdd.click();
        await workersCompensationWizard.governingLaw.selectOptionByLabel('State Act');
        await workersCompensationWizard.Location.selectOptionByLabel('1: 2287 Moore Avenue, Euless, TX');
        await t.click(workersCompensationWizard.classCodeSearch.component);
        await wcClassCodeSearchPopup.wCClassCodeSearchScreenClassCodeSearchResultsLV.clickOnCell(10,0);
        await workersCompensationWizard.basis.setValue('100000');
        
        //+----------WC Coverage Screen----------+
        await PcfButton(this.policyContractParent.find('div[id$="-WorkersCompSupplemental"]')).click();
        
        let numberOfSupplementalQuestion = await workersCompensationWizard.wcSupplementalQuestions.rowCount();
        
        for (let i = 0; i < numberOfSupplementalQuestion; i++) {
            
            await PcfComponent(workersCompensationWizard.wcSupplementalQuestions.component.find('td[id$="-'+i+'-QuestionModalInput-BooleanRadioInput_NoPost_Cell"]').find('input[id$="-BooleanRadioInput_NoPost_1"]')).click();
            
        }
        
        //+----------WC Options Screen----------+
        await PcfButton(this.policyContractParent.find('div[id$="-WorkersCompOptions"]')).click();
        await workersComp.submissionWizardLOBWizardStepGroupLineWizardStepSetCoverageOptionsScreenWCOptionsPanelSetOptionIteratorButton.click();

        await PcfButton(workersComp.submissionWizardLOBWizardStepGroupLineWizardStepSetCoverageOptionsScreenWCOptionsPanelSetOptionIteratorButton.component.find('div[id$="-CurrentOption"]').withText('Federal Liability')).click();
        await workersComp.submissionWizardLOBWizardStepGroupLineWizardStepSetCoverageOptionsScreenWCOptionsPanelSetWCOptionCardPanelSetWCFederalLiabilityInputSetWCLine_WCCovEmpLV_tbAdd.click();
        await workersCompensationWizard.flLocation.selectOptionByLabel('1: 2287 Moore Avenue, Euless, TX');
        await workersCompensationWizard.flClassCodeSearch.click();
        await wcClassCodeSearchPopup.wCClassCodeSearchScreenClassCodeSearchResultsLV.clickOnCell(2,0);
        await workersCompensationWizard.flBasis.setValue('100000');

        //+----------Risk Analysis Screen----------+
        await this.navigateToRiskAnalysis();
        
        await this.quotePolicy(); //Quoting the Policy
        
        //+----------Forns Screen----------+
        await this.navigateToFormScreen();
        
        //+----------Forns Screen----------+
        await this.navigateToPaymentScreen();

        await this.issuePolicy();

        world.InsuranceInfo.policyNumber = await this.policyTabBarParent.find('div[id$="-PolicyNumber"]').find('.gw-infoValue').innerText;// Getting the Policy Number

    }



}