module.exports = {
    contact: {
        firstName: "",
        lastName: "",
        name: "",
        taxID: ""
    },
    accountName: "",
    contactType: "",
    accountNumber: "",
    vehicleVin: ["1GDGG31V741901044","4V4VDBJG8TN730171"],
    policyNumber: "",
    effectiveDate: "",
    drivers: [],
    driverFirstName: ['Arnold', 'Lloyd'],
    driverLastName: ['Cabrera','Tagami'],
    dateOfBirth: ['06/10/1991', '08/06/1990'],
    maritalStatus: ['Single','Single'],
    addressLine: ['1827 W NEW RIVER RD','7007 W INDIAN SCHOOL RD'],
    city: ['PHOENIX','MESA'],
    state: ['Arizona','Arizona'],
    zipCode: ['85209', '85210'],
    addressType: ['Home','Home'],
    licenseNumber: ['D02267767','D03841206'],
    licenseState: ['Arizona','Arizona'],
    yearLicensed: ['2000', '2002'],
    numberOfAccidentsPolicyLevel: ['0','0'],
    numberOfViolationsPolicyLevel: ['0','0'],
    numberOfAccidentsAccountLevel: ['0','0'],
    numberOfViolationsAccountLevel: ['0','0'],
    listOFAddeddrivers:[],
    costNew: ['10000','20000'],
    //newVehicleVin: ['3VWSF71K96M764402','2C3CDYAG4EH185978','5TBBT44141S121440'],
    licenseStateInVehicle: ['Arizona','Arizona'],
    PreQualificationDropdown:  [['Is the applicant currently insured?','Yes']],
    PreQualificationRadioButton:  ['Is the applicant license currently suspended, canceled, or revoked?',
                               'Has the applicant license ever been canceled, suspended or revoked?',
                               'Any drivers with convictions for moving traffic violations within the past 3 years? If Yes please explain.',
                               'Has any policy or coverage been declined, canceled, or non-renewed during the prior 3 years?'],
                        
    
};