import { PcfComponent } from '@gtui/gt-ui-framework';
import { PcfTextInput } from '@gtui/gt-ui-framework';
import { PcfDateValueInput } from '@gtui/gt-ui-framework';
import { PcfSelectInput } from '@gtui/gt-ui-framework';
import { PcfButton } from '@gtui/gt-ui-framework';

export class VINLookup {
	vINLookupCancel = PcfButton('#VINLookup-Cancel');
	vINLookupEdit = PcfButton('#VINLookup-Edit');
	requestPolicyPullDVBodilyInjuryRatingSym = PcfTextInput('#VINLookup-RequestPolicyPullDV-BodilyInjuryRatingSym');
	requestPolicyPullDVBodilyInjuryRatingSymVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-BodilyInjuryRatingSymVIN');
	requestPolicyPullDVBodyStyke = PcfTextInput('#VINLookup-RequestPolicyPullDV-BodyStyke');
	requestPolicyPullDVBodyStyleRequest = PcfTextInput('#VINLookup-RequestPolicyPullDV-BodyStyleRequest');
	requestPolicyPullDVBodyStyleTextArea = PcfTextInput('#VINLookup-RequestPolicyPullDV-BodyStyleTextArea');
	requestPolicyPullDVCollIndSymAllModelYears = PcfTextInput('#VINLookup-RequestPolicyPullDV-CollIndSymAllModelYears');
	requestPolicyPullDVCollIndSymAllModelYearsVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-CollIndSymAllModelYearsVIN');
	requestPolicyPullDVCompIndSymAllModelYears = PcfTextInput('#VINLookup-RequestPolicyPullDV-CompIndSymAllModelYears');
	requestPolicyPullDVCompIndSymAllModelYearsVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-CompIndSymAllModelYearsVIN');
	requestPolicyPullDVCostNew_Ext = PcfTextInput('#VINLookup-RequestPolicyPullDV-CostNew_Ext');
	requestPolicyPullDVECylinder = PcfTextInput('#VINLookup-RequestPolicyPullDV-ECylinder');
	requestPolicyPullDVEffectiveDateInput = PcfDateValueInput('#VINLookup-RequestPolicyPullDV-EffectiveDateInput');
	requestPolicyPullDVEngineCylinderRequest = PcfTextInput('#VINLookup-RequestPolicyPullDV-EngineCylinderRequest');
	requestPolicyPullDVEngineCylinderTextArea = PcfTextInput('#VINLookup-RequestPolicyPullDV-EngineCylinderTextArea');
	requestPolicyPullDVFourWheelDriveIndicator = PcfTextInput('#VINLookup-RequestPolicyPullDV-FourWheelDriveIndicator');
	requestPolicyPullDVFourWheelDriveIndicatorRequest = PcfTextInput('#VINLookup-RequestPolicyPullDV-FourWheelDriveIndicatorRequest');
	requestPolicyPullDVFourWheelTextArea = PcfTextInput('#VINLookup-RequestPolicyPullDV-FourWheelTextArea');
	requestPolicyPullDVMake = PcfTextInput('#VINLookup-RequestPolicyPullDV-Make');
	requestPolicyPullDVMakeRequest = PcfTextInput('#VINLookup-RequestPolicyPullDV-MakeRequest');
	requestPolicyPullDVMakeTextArea = PcfTextInput('#VINLookup-RequestPolicyPullDV-MakeTextArea');
	requestPolicyPullDVMedicalPaymentsRatingSy = PcfTextInput('#VINLookup-RequestPolicyPullDV-MedicalPaymentsRatingSy');
	requestPolicyPullDVMedicalPaymentsRatingSyVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-MedicalPaymentsRatingSyVIN');
	requestPolicyPullDVModel = PcfTextInput('#VINLookup-RequestPolicyPullDV-Model');
	requestPolicyPullDVModelRequest = PcfTextInput('#VINLookup-RequestPolicyPullDV-ModelRequest');
	requestPolicyPullDVModelTextArea = PcfTextInput('#VINLookup-RequestPolicyPullDV-ModelTextArea');
	requestPolicyPullDVModelYear = PcfTextInput('#VINLookup-RequestPolicyPullDV-ModelYear');
	requestPolicyPullDVModelYearRequest = PcfTextInput('#VINLookup-RequestPolicyPullDV-ModelYearRequest');
	requestPolicyPullDVModelYearTextArea = PcfTextInput('#VINLookup-RequestPolicyPullDV-ModelYearTextArea');
	requestPolicyPullDVMwfbiCollFactor = PcfTextInput('#VINLookup-RequestPolicyPullDV-MwfbiCollFactor');
	requestPolicyPullDVMwfbiCollFactorVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-MwfbiCollFactorVIN');
	requestPolicyPullDVMwfbiCompFactor = PcfTextInput('#VINLookup-RequestPolicyPullDV-MwfbiCompFactor');
	requestPolicyPullDVMwfbiCompFactorVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-MwfbiCompFactorVIN');
	requestPolicyPullDVMwfbiLiabFactor = PcfTextInput('#VINLookup-RequestPolicyPullDV-MwfbiLiabFactor');
	requestPolicyPullDVMwfbiLiabFactorVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-MwfbiLiabFactorVIN');
	requestPolicyPullDVMwfbiMedFactor = PcfTextInput('#VINLookup-RequestPolicyPullDV-MwfbiMedFactor');
	requestPolicyPullDVMwfbiMedFactorVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-MwfbiMedFactorVIN');
	requestPolicyPullDVPolicyStatus = PcfTextInput('#VINLookup-RequestPolicyPullDV-PolicyStatus');
	requestPolicyPullDVStateCode = PcfTextInput('#VINLookup-RequestPolicyPullDV-StateCode');
	requestPolicyPullDVStatedValue = PcfTextInput('#VINLookup-RequestPolicyPullDV-StatedValue');
	requestPolicyPullDVVIN = PcfTextInput('#VINLookup-RequestPolicyPullDV-VIN');
	requestPolicyPullDVVehicleTypeID = PcfSelectInput('#VINLookup-RequestPolicyPullDV-VehicleTypeID');
	requestPolicyPullDVgetBodyStyle = PcfButton('#VINLookup-RequestPolicyPullDV-getBodyStyle');
	requestPolicyPullDVgetEngine = PcfButton('#VINLookup-RequestPolicyPullDV-getEngine');
	requestPolicyPullDVgetFourWheelDrive = PcfButton('#VINLookup-RequestPolicyPullDV-getFourWheelDrive');
	requestPolicyPullDVgetMake = PcfButton('#VINLookup-RequestPolicyPullDV-getMake');
	requestPolicyPullDVgetModel = PcfButton('#VINLookup-RequestPolicyPullDV-getModel');
	requestPolicyPullDVgetModelYear = PcfButton('#VINLookup-RequestPolicyPullDV-getModelYear');
	requestPolicyPullDVgetSymbolsUsingStatedValue = PcfButton('#VINLookup-RequestPolicyPullDV-getSymbolsUsingStatedValue');
	requestPolicyPullDVgetSymbolsUsingVIF = PcfButton('#VINLookup-RequestPolicyPullDV-getSymbolsUsingVIF');
	requestPolicyPullDVgetVehicleDetailsByVINTEST = PcfButton('#VINLookup-RequestPolicyPullDV-getVehicleDetailsByVINTEST');
	vINLookupRequestPolicyPullDVresetFields = PcfButton('#VINLookup-RequestPolicyPullDV-resetFields');
	requestPolicyPullDVresetSymbolFields = PcfButton('#VINLookup-RequestPolicyPullDV-resetSymbolFields');
	requestPolicyPullDVresetVIFValues = PcfButton('#VINLookup-RequestPolicyPullDV-resetVIFValues');
	vINLookupUpdate = PcfButton('#VINLookup-Update');
	vINLookupVINLookup_UpLink = PcfButton('#VINLookup-VINLookup_UpLink');
	vINLookup_Paging = PcfButton('#VINLookup-_Paging');
	vINLookup__crumb__ = PcfComponent('#VINLookup-__crumb__');
	vINLookup_msgs = PcfButton('#VINLookup-_msgs');
}
